const express = require('express');
const cloudinary = require('cloudinary').v2;

const app = express();
const port = 3000;

cloudinary.config({
  cloud_name: 'profj001',
  api_key: '423589193815927',
  api_secret: 'KO1VNau0GmqX-9YI6qHuBwu6870'
});

app.get('/', (req, res, next) => {
  res.json('Hello from cloudinary test');
});

cloudinary.uploader.upload(
  './uploads/2019-11-15T12-40-21.152Zflower.jpeg',
  { tags: 'basic_sample' },
  function(err, image) {
    console.log();
    console.log('** File Upload');
    if (err) {
      console.warn(err);
    }
    console.log(
      "* public_id for the uploaded image is generated by Cloudinary's service."
    );
    console.log('* ' + image.public_id);
    console.log('* ' + image.url);
  }
);

app.listen(port, () => {
  console.log(`Listening on port ${port}`);
});
